AWSTemplateFormatVersion: '2010-09-09'
Description: Infosec Security Audit and Incident Response Roles
Metadata:
  Source: https://github.com/mozilla/security/tree/master/operations/aws-security-auditor
  LambdaFunctionSource: https://github.com/mozilla/security/tree/master/operations/lambda_functions/publish_to_sns
Resources:
  InfosecSecurityAuditRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::371522382791:root
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecurityAudit
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - autoscaling:Describe*
                  - cloudformation:DescribeStack*
                  - cloudformation:GetTemplate
                  - cloudformation:ListStack*
                  - cloudfront:Get*
                  - cloudfront:List*
                  - cloudtrail:DescribeTrails
                  - cloudtrail:GetTrailStatus
                  - cloudwatch:Describe*
                  - directconnect:Describe*
                  - dynamodb:ListTables
                  - ec2:Describe*
                  - elasticbeanstalk:Describe*
                  - elasticache:Describe*
                  - elasticloadbalancing:Describe*
                  - elasticmapreduce:Describe*
                  - elasticmapreduce:List*
                  - glacier:ListVaults
                  - iam:Get*
                  - iam:List*
                  - rds:Describe*
                  - rds:DownloadDBLogFilePortion
                  - rds:ListTagsForResource
                  - redshift:Describe*
                  - route53:GetHostedZone
                  - route53:ListHostedZones
                  - route53:ListResourceRecordSets
                  - s3:GetBucket*
                  - s3:GetLifecycleConfiguration
                  - s3:GetObjectAcl
                  - s3:GetObjectVersionAcl
                  - s3:List*
                  - sdb:DomainMetadata
                  - sdb:ListDomains
                  - ses:Get*
                  - ses:List*
                  - sns:GetTopicAttributes
                  - sns:ListTopics
                  - sqs:GetQueueAttributes
                  - sqs:ListQueues
                  - storagegateway:List*
                  - storagegateway:Describe*
                Effect: Allow
                Resource: '*'
  InfosecIncidentResponseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::371522382791:root
            Action: sts:AssumeRole
      Policies:
        - PolicyName: IncidentResponseSnapshotDisk
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ec2:CreateSnapshot
                  - ec2:DescribeSnapshots
                  - ec2:CreateVolume
                  - ec2:DescribeVolumes
                  - ec2:DescribeVolumeStatus
                Effect: Allow
                Resource: '*'
        - PolicyName: IncidentResponseCreateForensicsInstance
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ec2:RunInstances
                  - ec2:DescribeImages
                  - ec2:ImportKeyPair
                  - ec2:CreateSecurityGroup
                  - ec2:AttachVolume
                Effect: Allow
                Resource: '*'
        - PolicyName: IncidentResponseSequesterInstance
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ec2:ModifyInstanceAttribute
                Effect: Allow
                Resource: '*'
        - PolicyName: IncidentResponseEnableMemoryExport
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:DescribeSecurityGroups
                  - ec2:CreateSecurityGroup
                  - ec2:RevokeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupIngress
                Effect: Allow
                Resource: '*'
  PublishToSNSInfo:
    Type: Custom::PublishToSNSInfo
    Properties:
      ServiceToken: !GetAtt 'PublishToSNS.Arn'
      TopicArn: arn:aws:sns:us-west-2:371522382791:AccountUpdates
      Message: !Join
        - ''
        - - '{"Incident Response Role ARN": "'
          - !GetAtt 'InfosecIncidentResponseRole.Arn'
          - '", "Security Audit Role ARN": "'
          - !GetAtt 'InfosecSecurityAuditRole.Arn'
          - '"}'
  PublishToSNS:
    Type: AWS::Lambda::Function
    Properties:
      Handler: publish_to_sns.publish_to_sns
      Role: !GetAtt 'LambdaExecutionRole.Arn'
      Code:
        S3Bucket: !Join
          - '-'
          - - infosec-lambda
            - !Ref 'AWS::Region'
        S3Key: publish_to_sns.zip
      Runtime: python2.7
      Timeout: '30'
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - logs:DeleteLogGroup
                Resource: !Join
                  - ''
                  - - 'arn:aws:logs:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - :log-group:/aws/lambda/*
Outputs:
  InfosecSecurityAuditRoleARN:
    Value: !GetAtt 'InfosecSecurityAuditRole.Arn'
    Description: The ARN of the new Infosec Security Audit Role
  InfosecIncidentResponseRoleARN:
    Value: !GetAtt 'InfosecIncidentResponseRole.Arn'
    Description: The ARN of the new Infosec Incident Response Role
