AWSTemplateFormatVersion: '2010-09-09'
Description: Mozilla federated ReadOnly IAM roles to aid in the 2020 IAM pentest
Metadata:
  Source: https://github.com/mozilla/security/tree/master/operations/cloudformation-templates/iam-pentest-read-role.yml
  JiraIssue: https://jira.mozilla.com/browse/EIS-1768
Resources:
  AdminIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MAWS-2020IAMPenTest
      Description: !Join [ '', [ 'ReadOnlyAccess Federated IAM Role which culucenk is permitted to assume. This Role enables viewing sensitive data like S3 file contents, DynamoDB table contents, etc']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              Federated: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':oidc-provider/auth.mozilla.auth0.com/' ]]
            Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Condition:
              StringEquals:
                auth.mozilla.auth0.com/:aud: N7lULzWtfVUDGymwDs0yDEq6ZcwmFazj
              ForAnyValue:StringEquals:
                auth.mozilla.auth0.com/:amr:
                  - mozilliansorg_2020-iam-pentest
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess