AWSTemplateFormatVersion: 2010-09-09
Description: IAM Admin Role which trusts infosec-prod
Metadata:
  Source: https://github.com/mozilla/security/tree/master/operations/cloudformation-templates
Mappings:
  VariablesMap:
    Infosec:
      ProdAccountId: '371522382791'
Resources:
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Join
                - ':'
                - - 'arn:aws:iam:'
                  - !FindInMap
                    - VariablesMap
                    - Infosec
                    - ProdAccountId
                  - root
            Condition:
              StringEquals:
                aws:PrincipalType: User
              Bool:
                aws:MultiFactorAuthPresent: true
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: InfosecAdmin
