AWSTemplateFormatVersion: 2010-09-09
Description: Create Enterprise Information Security Dev S3 Buckets in us-east-1.
Metadata:
  Source: https://github.com/mozilla/security/tree/master/operations/cloudformation-templates/infosec_dev_s3_buckets_us-east-1.yml
Rules:
  CorrectRegionAndAccount:
    RuleCondition: !Equals [ '1', '1' ]
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This template deploys us-east-1 resources and must be depoyed only in us-east-1
      - Assert: !Equals [ !Ref 'AWS::AccountId', '656532927350' ]
        AssertDescription: This template deploys infosec-dev resources and must be depoyed only in infosec-dev 656532927350 AWS account
Resources:
  PublicUsEast1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: public.us-east-1.security.allizom.org
      VersioningConfiguration:
        Status: Enabled  # This is required for bucket replication
      Tags:
        - Key: S3 Bucket Replication Note
          Value: This bucket is replicated from public.us-west-2.security.allizom.org. Do not add or modify files in this bucket. Instead do so in the public.us-west-2.security.allizom.org bucket and it will be replicated here.
  PublicUsEast1BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicUsEast1
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: arn:aws:s3:::public.us-east-1.security.allizom.org/*
