AWSTemplateFormatVersion: '2010-09-09'
Description: Mozilla federated Admin ReadOnly ViewOnly SecurityAuditor and GuardDutyReader IAM roles
Metadata:
  Source: https://github.com/mozilla/security/tree/master/operations/cloudformation-templates/infosec-prod_oidc_federated_roles.yaml
Resources:
  AdminIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MAWS-Admin
      Description: !Join [ '', [ 'AdministratorAccess Federated IAM Role which the group team_opsec is permitted to assume']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              Federated: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':oidc-provider/auth.mozilla.auth0.com/' ]]
            Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Condition:
              StringEquals:
                auth.mozilla.auth0.com/:aud: N7lULzWtfVUDGymwDs0yDEq6ZcwmFazj
              ForAnyValue:StringEquals:
                auth.mozilla.auth0.com/:amr:
                  - team_opsec
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      MaxSessionDuration: 43200  # 12 hours
  ReadOnlyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MAWS-ReadOnly
      Description: !Join [ '', [ 'ReadOnlyAccess Federated IAM Role which the group team_opsec is permitted to assume. This Role enables viewing sensitive data like S3 file contents, DynamoDB table contents, etc']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              Federated: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':oidc-provider/auth.mozilla.auth0.com/' ]]
            Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Condition:
              StringEquals:
                auth.mozilla.auth0.com/:aud: N7lULzWtfVUDGymwDs0yDEq6ZcwmFazj
              ForAnyValue:StringEquals:
                auth.mozilla.auth0.com/:amr:
                  - team_opsec
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      MaxSessionDuration: 43200  # 12 hours
  ViewOnlyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MAWS-ViewOnly
      Description: !Join [ '', [ 'ViewOnlyAccess Federated IAM Role which the group team_opsec is permitted to assume. This Role enables viewing only resource metadata, not sensitive data like S3 file contents']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              Federated: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':oidc-provider/auth.mozilla.auth0.com/' ]]
            Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Condition:
              StringEquals:
                auth.mozilla.auth0.com/:aud: N7lULzWtfVUDGymwDs0yDEq6ZcwmFazj
              ForAnyValue:StringEquals:
                auth.mozilla.auth0.com/:amr:
                  - team_opsec
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      MaxSessionDuration: 43200  # 12 hours
  SecurityAuditorIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MAWS-SecurityAuditor
      Description: !Join [ '', [ 'SecurityAuditor Federated IAM Role which the group team_opsec and team_secops is permitted to assume. This Role enables assuming security audit roles in other accounts']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              Federated: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':oidc-provider/auth.mozilla.auth0.com/' ]]
            Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Condition:
              StringEquals:
                auth.mozilla.auth0.com/:aud: N7lULzWtfVUDGymwDs0yDEq6ZcwmFazj
              ForAnyValue:StringEquals:
                auth.mozilla.auth0.com/:amr:
                  - team_opsec
                  - team_secops
      PermissionsBoundary: !Ref SecurityAuditPolicy
      MaxSessionDuration: 43200  # 12 hours
  SecurityAuditorRoleAssumer:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
            Resource:
            - arn:aws:dynamodb:us-west-2:371522382791:table/cloudformation-stack-emissions
            - arn:aws:dynamodb:us-west-2:371522382791:table/cloudformation-stack-emissions/*
            Condition:
              "ForAllValues:StringEquals":
                "dynamodb:Attributes":
                  - aws-account-id
                  - id
                  - category
                  - SecurityAuditIAMRoleArn
                  - SecurityAuditIAMRoleName
              StringEqualsIfExists:
                "dynamodb:Select": SPECIFIC_ATTRIBUTES
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource: '*'
      PolicyName: SecurityAuditorRoleAssumer
      Roles:
        - !Ref SecurityAuditorIAMRole
  SecurityAuditPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      # Source https://github.com/mozilla/security/tree/master/operations/aws-security-roles/eis-security-audit-trusting-role.yml
      ManagedPolicyName: SecurityAudit
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - acm-pca:List*
              - acm:Describe*
              - acm:List*
              - autoscaling:Describe*
              - aws-portal:View*
              - awsbillingconsole:View*
              - cloudformation:Describe*
              - cloudformation:Get*
              - cloudformation:List*
              - cloudfront:Get*
              - cloudfront:List*
              - cloudtrail:Describe*
              - cloudtrail:Get*
              - cloudtrail:List*
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              - config:Describe*
              - config:Get*
              - config:List*
              - directconnect:Describe*
              - dynamodb:Describe*
              - dynamodb:List*
              - ec2:Describe*
              - ecs:Describe*
              - ecs:List*
              - elasticache:Describe*
              - elasticbeanstalk:Describe*
              - elasticloadbalancing:Describe*
              - elasticmapreduce:Describe*
              - elasticmapreduce:List*
              - es:Describe*
              - es:Get*
              - es:List*
              - glacier:Describe*
              - glacier:GetVaultAccessPolicy
              - glacier:List*
              - guardduty:Get*
              - guardduty:List*
              - iam:Get*
              - iam:List*
              - iam:Simulate*
              - inspector:Describe*
              - inspector:Get*
              - inspector:List*
              - kms:Describe*
              - kms:GetKey*
              - kms:List*
              - lambda:GetFunctionConfiguration
              - lambda:GetLayerVersionPolicy
              - lambda:GetPolicy
              - lambda:List*
              - rds:Describe*
              - rds:DownloadDBLogFilePortion
              - rds:ListTagsForResource
              - redshift:Describe*
              - route53:GetHostedZone
              - route53:ListHostedZones
              - route53:ListResourceRecordSets
              - route53domains:GetDomainDetail
              - route53domains:ListDomains
              - s3:GetAccelerateConfiguration
              - s3:GetAnalyticsConfiguration
              - s3:GetBucket*
              - s3:GetEncryptionConfiguration
              - s3:GetInventoryConfiguration
              - s3:GetLifecycleConfiguration
              - s3:GetLifecycleConfiguration
              - s3:GetMetricsConfiguration
              - s3:GetObjectAcl
              - s3:GetObjectVersionAcl
              - s3:GetReplicationConfiguration
              - s3:List*
              - sdb:DomainMetadata
              - sdb:ListDomains
              - ses:Get*
              - ses:List*
              - sns:GetTopicAttributes
              - sns:ListSubscriptionsByTopic
              - sns:ListTopics
              - sqs:Get*
              - sqs:List*
              - ssm:DescribeAutomationExecutions
              - ssm:DescribeInstance*
              - ssm:DescribePatch*
              - ssm:ListAssociation*
              - storagegateway:Describe*
              - storagegateway:List*
              - support:DescribeTrustedAdvisor*
            Effect: Allow
            Resource: '*'
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
            Resource:
              - arn:aws:dynamodb:us-west-2:371522382791:table/cloudformation-stack-emissions
              - arn:aws:dynamodb:us-west-2:371522382791:table/cloudformation-stack-emissions/*
            Condition:
              "ForAllValues:StringEquals":
                "dynamodb:Attributes":
                  - aws-account-id
                  - id
                  - category
                  - SecurityAuditIAMRoleArn
                  - SecurityAuditIAMRoleName
              StringEqualsIfExists:
                "dynamodb:Select": SPECIFIC_ATTRIBUTES
  GuardDutyReaderIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MAWS-GuardDutyReader
      Description: !Join [ '', [ 'AmazonGuardDutyReadOnlyAccess Federated IAM Role which the groups team_opsec and team_secops are permitted to assume. This Role enables read access to the GuardDuty parent in the infosec-prod AWS account']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              Federated: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':oidc-provider/auth.mozilla.auth0.com/' ]]
            Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Condition:
              StringEquals:
                auth.mozilla.auth0.com/:aud: N7lULzWtfVUDGymwDs0yDEq6ZcwmFazj
              ForAnyValue:StringEquals:
                auth.mozilla.auth0.com/:amr:
                  - team_opsec
                  - team_secops
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonGuardDutyReadOnlyAccess
      MaxSessionDuration: 43200  # 12 hours