AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to create the group granting it's members
  to administer the infosec-malware-detonation AWS account
Metadata:
  Source: https://github.com/mozilla/security/tree/master/operations/cloudformation-templates
Mappings:
  VariablesMap:
    Infosec:
      MalwareDetonationAccountId: '298283239067'
Resources:
  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy which grants users rights to the malware detonation
        admin role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
            Resource: !Join
              - ':'
              - - 'arn:aws:iam:'
                - !FindInMap
                  - VariablesMap
                  - Infosec
                  - MalwareDetonationAccountId
                - role/InfosecAdmin
  Group:
    Metadata:
      Notes1: This group grants members rights to assume the InfosecAdmin role in
        the infosec-malware-detonation account
    Type: AWS::IAM::Group
    Properties:
      GroupName: InfosecMalwareDetonationAdminUserGroup
      ManagedPolicyArns:
        - !Ref Policy
