AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role to read contents of S3 bucket containing CloudTrail logs
Metadata:
  Source: https://github.com/mozilla/security/tree/master/operations/aws-cloudtrail-storage
Resources:
  S3CloudTrailReaderPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Read CloudTrail S3 buckets
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation
            Resource: '*'
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - arn:aws:s3:::mozilla-cloudtrail-logs
          - Effect: Allow
            Action:
              - s3:Get*
            Resource:
              - arn:aws:s3:::mozilla-cloudtrail-logs/*
          - Effect: Allow
            Action:
              - athena:*
            Resource: '*'
          - Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:ListMultipartUploadParts
              - s3:AbortMultipartUpload
              - s3:PutObject
            Resource: arn:aws:s3:::aws-athena-query-results-088944123687-*
          - Effect: Allow
            Action:
              - glue:CreateDatabase
              - glue:DeleteDatabase
              - glue:GetDatabase
              - glue:GetDatabases
              - glue:UpdateDatabase
              - glue:CreateTable
              - glue:DeleteTable
              - glue:BatchDeleteTable
              - glue:UpdateTable
              - glue:GetTable
              - glue:GetTables
              - glue:BatchCreatePartition
              - glue:CreatePartition
              - glue:DeletePartition
              - glue:BatchDeletePartition
              - glue:UpdatePartition
              - glue:GetPartition
              - glue:GetPartitions
              - glue:BatchGetPartition
            Resource: '*'
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::371522382791:root
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref S3CloudTrailReaderPolicy
      RoleName: CloudTrail-Global-Log-Consumers
