AWSTemplateFormatVersion: '2010-09-09'
Description: Infosec Security Audit, Incident Response and GuardDuty Member Roles
Metadata:
  Source: https://github.com/mozilla/security/tree/master/operations/aws-security-roles/infosec-security-audit-incident-response-guardduty-roles-cloudformation.yml
Parameters:
  EmailAddress:
    Type: String
    Default: ''
    Description: An optional email address to subscribe to notifications of use of the Incident Response role
Mappings:
  Variables:
    SNSTopicForPublishingStackOutput:
      Account: 371522382791
      Topic: cloudformation-stack-emissions
    TrustedEISAccount:
      AccountId: 415589142697
    AllowedSNSSubscriber:
      AccountId: 371522382791
    GuardDutyMasterAccount:
      Principal: arn:aws:iam::371522382791:root
  TheRegionYouAreDeployingIn:
    us-west-2:
      WhatIsThisMapping: This constrains the regions in which you can deploy this template to only the regions listed in this mapping. This, for example, prevents deploying in ap-south-1
      IsNotSupportedPleaseUseADifferentRegion: True
    us-east-1:
      WhatIsThisMapping: ''
      IsNotSupportedPleaseUseADifferentRegion: True
    us-west-1:
      WhatIsThisMapping: ''
      IsNotSupportedPleaseUseADifferentRegion: True
    eu-west-1:
      WhatIsThisMapping: ''
      IsNotSupportedPleaseUseADifferentRegion: True
Conditions:
  EmailAddressIsPresent: !Not [ !Equals [ !Ref EmailAddress, '' ] ]
  RunningInAllowedRegion: !Equals [ !FindInMap [ TheRegionYouAreDeployingIn, !Ref 'AWS::Region', IsNotSupportedPleaseUseADifferentRegion ] , True ]
Resources:
  InfosecSecurityAuditRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::371522382791:root
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecurityAudit
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - acm-pca:List*
                  - acm:Describe*
                  - acm:List*
                  - autoscaling:Describe*
                  - aws-portal:View*
                  - awsbillingconsole:View*
                  - cloudformation:Describe*
                  - cloudformation:Get*
                  - cloudformation:List*
                  - cloudfront:Get*
                  - cloudfront:List*
                  - cloudtrail:Describe*
                  - cloudtrail:Get*
                  - cloudtrail:List*
                  - cloudwatch:Describe*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                  - config:Describe*
                  - config:Get*
                  - config:List*
                  - directconnect:Describe*
                  - dynamodb:Describe*
                  - dynamodb:List*
                  - ec2:Describe*
                  - ecs:Describe*
                  - ecs:List*
                  - elasticache:Describe*
                  - elasticbeanstalk:Describe*
                  - elasticloadbalancing:Describe*
                  - elasticmapreduce:Describe*
                  - elasticmapreduce:List*
                  - es:Describe*
                  - es:Get*
                  - es:List*
                  - glacier:Describe*
                  - glacier:GetVaultAccessPolicy
                  - glacier:List*
                  - guardduty:Get*
                  - guardduty:List*
                  - iam:Get*
                  - iam:List*
                  - iam:Simulate*
                  - inspector:Describe*
                  - inspector:Get*
                  - inspector:List*
                  - kms:Describe*
                  - kms:GetKey*
                  - kms:List*
                  - lambda:GetFunctionConfiguration
                  - lambda:GetLayerVersionPolicy
                  - lambda:GetPolicy
                  - lambda:List*
                  - rds:Describe*
                  - rds:DownloadDBLogFilePortion
                  - rds:ListTagsForResource
                  - redshift:Describe*
                  - route53:GetHostedZone
                  - route53:ListHostedZones
                  - route53:ListResourceRecordSets
                  - route53domains:GetDomainDetail
                  - route53domains:ListDomains
                  - s3:GetAccelerateConfiguration
                  - s3:GetAnalyticsConfiguration
                  - s3:GetBucket*
                  - s3:GetEncryptionConfiguration
                  - s3:GetInventoryConfiguration
                  - s3:GetLifecycleConfiguration
                  - s3:GetLifecycleConfiguration
                  - s3:GetMetricsConfiguration
                  - s3:GetObjectAcl
                  - s3:GetObjectVersionAcl
                  - s3:GetReplicationConfiguration
                  - s3:List*
                  - sdb:DomainMetadata
                  - sdb:ListDomains
                  - ses:Get*
                  - ses:List*
                  - sns:GetTopicAttributes
                  - sns:ListSubscriptionsByTopic
                  - sns:ListTopics
                  - sqs:Get*
                  - sqs:List*
                  - ssm:DescribeAutomationExecutions
                  - ssm:DescribeInstance*
                  - ssm:DescribePatch*
                  - ssm:ListAssociation*
                  - storagegateway:Describe*
                  - storagegateway:List*
                  - support:DescribeTrustedAdvisor*
                Effect: Allow
                Resource: '*'
  PublishInfosecSecurityAuditRoleArnToSNS:
    Type: Custom::PublishInfosecSecurityAuditRoleArnToSNS
    Version: '1.0'
    Properties:
      ServiceToken: !Join [ ':', [ 'arn:aws:sns', !Ref 'AWS::Region', !FindInMap [ Variables, SNSTopicForPublishingStackOutput, Account ], !FindInMap [ Variables, SNSTopicForPublishingStackOutput, Topic ] ] ]
      category: AWS Security Auditing Service
      SecurityAuditIAMRoleArn: !GetAtt InfosecSecurityAuditRole.Arn
      SecurityAuditIAMRoleName: !Ref InfosecSecurityAuditRole
  InfosecIncidentResponseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowEISTrustedToAssume
            Effect: Allow
            Principal:
              AWS: !Join [ '', [ 'arn:aws:iam::', !FindInMap [ Variables, TrustedEISAccount, AccountId ], ':root' ] ]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  BreakGlassTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Notifications of use of the EIS Incident Response IAM Role
      TopicName: EISIncidentResponseBreakGlass
  BreakGlassTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref BreakGlassTopic
      PolicyDocument:
        Version: 2012-10-17
        Id: BreakGlassPolicy
        Statement:
          - Action: sns:Publish
            Principal:
              AWS:
                - !Join [ '', [ 'arn:aws:iam::', !FindInMap [ Variables, TrustedEISAccount, AccountId ], ':root' ] ]
            Resource: !Ref BreakGlassTopic
            Effect: Allow
            Sid: BreakGlassPublisher
          - Action: sns:Publish
            Principal: '*'
            Resource: !Ref BreakGlassTopic
            Effect: Allow
            Sid: BreakGlassServicePublisher
            Condition:
              StringEquals:
                'AWS:SourceAccount': !FindInMap [ Variables, TrustedEISAccount, AccountId ]
          - Action:
              - sns:GetTopicAttributes
              - sns:ListSubscriptionsByTopic
              - sns:Subscribe
            Principal:
              AWS:
                - !Join [ '', [ 'arn:aws:iam::', !FindInMap [ Variables, AllowedSNSSubscriber, AccountId ], ':root' ] ]
                - !Join [ '', [ 'arn:aws:iam::', !FindInMap [ Variables, TrustedEISAccount, AccountId ], ':root' ] ]
            Resource: !Ref BreakGlassTopic
            Effect: Allow
            Sid: BreakGlassSubscriber
  OptionalEmailSubscription:
    Type: "AWS::SNS::Subscription"
    Condition: EmailAddressIsPresent
    Properties:
      Endpoint: !Ref EmailAddress
      Protocol: email
      TopicArn: !Ref BreakGlassTopic
  PublishInfosecIncidentResponseInfoToSNS:
    Type: Custom::PublishInfosecIncidentResponseInfoToSNS
    Version: '1.0'
    Properties:
      ServiceToken: !Join [ ':', [ 'arn:aws:sns', !Ref 'AWS::Region', !FindInMap [ Variables, SNSTopicForPublishingStackOutput, Account ], !FindInMap [ Variables, SNSTopicForPublishingStackOutput, Topic ] ] ]
      category: AWS Incident Response Service
      InfosecIncidentResponseRoleArn: !GetAtt InfosecIncidentResponseRole.Arn
      InfosecIncidentResponseRoleName: !Ref InfosecIncidentResponseRole
      BreakGlassSNSTopicArn: !Ref BreakGlassTopic
      BreakGlassSNSTopicName: !GetAtt BreakGlassTopic.TopicName
Outputs:
  InfosecSecurityAuditRoleARN:
    Value: !GetAtt 'InfosecSecurityAuditRole.Arn'
    Description: The ARN of the new Infosec Security Audit Role
  InfosecIncidentResponseRoleARN:
    Value: !GetAtt 'InfosecIncidentResponseRole.Arn'
    Description: The ARN of the new Infosec Incident Response Role
